version : '2'
services:
    client:
        build:
            context: client/
            dockerfile: Dockerfile
        container_name: client
        ports:
            - "8080:8080"
        depends_on:
            - server

    server:
        build:
            context: server/
            dockerfile: Dockerfile
        container_name: server
        ports:
            - "3030:3030"
        depends_on:
            - database

    database:
        image: mongo
        ports:
            - "27017:27017"
        volumes:
            - mongo_volume:/data/db

volumes:
    mongo_volume:
